from datetime import date

PEOPLE = {
    "Arjun Malhotra": ("VP Sales", "arjun.malhotra@veridian-corp.example"),
    "Neha Kapoor": ("Marketing Lead", "neha.kapoor@veridian-corp.example"),
    "Raghav Sethi": ("Ops Manager", "raghav.sethi@veridian-corp.example"),
    "Divya Rao": ("Finance", "divya.rao@veridian-corp.example"),
    "Priya Nair": ("Meridian Logistics (external client)", "priya.nair@meridianlogistics.example"),
    "Facilities": ("Internal distribution list", "facilities@veridian-corp.example"),
}

COMMITMENTS = [
    {
        "id": "vendor",
        "title": "Send updated vendor list",
        "owner": "Arjun Malhotra",
        "recipient": "Raghav Sethi",
        "deadline": "Wednesday morning",
        "deadline_date": date(2026, 9, 23),
        "status": "Unresolved",
        "priority": "High",
        "latest_evidence": "Raghav checked at 8:45 AM Wednesday asking whether it was still good for that morning. No later confirmation of delivery appears in the source data.",
        "sources": ["Leadership Sync", "Vendor List email thread", "Voice Note 1"],
        "next_action": "Confirm whether the vendor list was sent; if not, send it to Raghav.",
    },
    {
        "id": "deck",
        "title": "Q3 campaign deck review",
        "owner": "Arjun Malhotra",
        "recipient": "Neha Kapoor",
        "deadline": "Thursday 9:30 AM",
        "deadline_date": date(2026, 9, 24),
        "status": "Scheduled / ready",
        "priority": "Medium",
        "latest_evidence": "Neha said the review would be Thursday at 9:30 AM and sent the ready deck at 8:00 AM Thursday.",
        "sources": ["Leadership Sync", "Q3 Campaign Deck email thread", "Arjun calendar"],
        "next_action": "Review the deck at the scheduled 9:30 AM meeting.",
    },
    {
        "id": "expense",
        "title": "July expense variance report",
        "owner": "Divya Rao",
        "recipient": "Arjun Malhotra",
        "deadline": "Wednesday evening",
        "deadline_date": date(2026, 9, 23),
        "status": "Completed",
        "priority": "Done",
        "latest_evidence": "Divya sent the report at 6:00 PM Wednesday; Arjun acknowledged receipt at 6:10 PM.",
        "sources": ["Leadership Sync", "Expense Variance Report email thread", "Voice Note 2"],
        "next_action": "No outstanding delivery action is shown in the source.",
    },
    {
        "id": "meridian",
        "title": "Meridian Logistics client call",
        "owner": "Arjun Malhotra",
        "recipient": "Priya Nair",
        "deadline": "Wednesday 3:00 PM",
        "deadline_date": date(2026, 9, 23),
        "status": "Confirmed",
        "priority": "Confirmed",
        "latest_evidence": "Priya confirmed Wednesday 3:00 PM, and Arjun reconfirmed the call at 2:00 PM Wednesday.",
        "sources": ["Leadership Sync", "Call Reschedule email thread", "Voice Note 2", "Arjun calendar"],
        "next_action": "Attend the confirmed 3:00 PM call.",
    },
    {
        "id": "lease",
        "title": "Mumbai office lease renewal signature",
        "owner": "Unassigned",
        "recipient": "Facilities",
        "deadline": "Friday, 25 September, end of day",
        "deadline_date": date(2026, 9, 25),
        "status": "Critical / unowned",
        "priority": "Critical",
        "latest_evidence": "Facilities said the authorized signature was still pending Thursday at 4:00 PM; Raghav said at 4:45 PM that it was still unowned.",
        "sources": ["Leadership Sync", "Mumbai Office Lease Renewal email thread"],
        "next_action": "Confirm who is authorized to own/sign off the renewal before the Friday deadline.",
    },
]

CALENDAR = [
    ("Arjun Malhotra", "Mon 21 Sep", "9:00–9:35 AM", "Leadership Sync"),
    ("Arjun Malhotra", "Mon 21 Sep", "2:00–2:30 PM", "1:1 with Neha"),
    ("Arjun Malhotra", "Mon 21 Sep", "4:00–5:00 PM", "Blocked"),
    ("Arjun Malhotra", "Tue 22 Sep", "11:00 AM–12:00 PM", "Internal Budget Review"),
    ("Arjun Malhotra", "Tue 22 Sep", "3:00–3:30 PM", "Blocked"),
    ("Arjun Malhotra", "Wed 23 Sep", "3:00–3:30 PM", "Call — Meridian Logistics"),
    ("Arjun Malhotra", "Wed 23 Sep", "6:00–6:15 PM", "Blocked"),
    ("Arjun Malhotra", "Thu 24 Sep", "9:00–10:00 AM", "Board Prep Session"),
    ("Arjun Malhotra", "Thu 24 Sep", "4:00–5:00 PM", "Hiring Panel — Sales Associate"),
    ("Arjun Malhotra", "Fri 25 Sep", "10:00–10:30 AM", "Facilities Check-in"),
    ("Arjun Malhotra", "Fri 25 Sep", "1:00–2:00 PM", "Blocked"),
    ("Neha Kapoor", "Mon 21 Sep", "10:00–11:00 AM", "Blocked"),
    ("Neha Kapoor", "Mon 21 Sep", "2:00–2:30 PM", "1:1 with Arjun"),
    ("Neha Kapoor", "Tue 22 Sep", "1:00–2:00 PM", "Campaign Vendor Call"),
    ("Neha Kapoor", "Wed 23 Sep", "10:00–10:30 AM", "Deck Prep"),
    ("Neha Kapoor", "Wed 23 Sep", "1:00–3:00 PM", "Blocked"),
    ("Neha Kapoor", "Thu 24 Sep", "9:30–10:00 AM", "Deck Review with Arjun"),
    ("Neha Kapoor", "Fri 25 Sep", "11:00 AM–12:00 PM", "Blocked"),
    ("Raghav Sethi", "Mon 21 Sep", "9:00–9:35 AM", "Leadership Sync"),
    ("Raghav Sethi", "Mon 21 Sep", "1:00–2:00 PM", "Blocked"),
    ("Raghav Sethi", "Tue 22 Sep", "11:00 AM–12:00 PM", "Internal Budget Review"),
    ("Raghav Sethi", "Tue 22 Sep", "3:30–4:00 PM", "Ops Standup"),
    ("Raghav Sethi", "Wed 23 Sep", "9:00–11:00 AM", "Blocked"),
    ("Raghav Sethi", "Thu 24 Sep", "2:00–3:00 PM", "Blocked"),
    ("Raghav Sethi", "Fri 25 Sep", "10:00–10:30 AM", "Facilities Check-in"),
    ("Raghav Sethi", "Fri 25 Sep", "3:00–4:00 PM", "Blocked"),
    ("Divya Rao", "Mon 21 Sep", "2:30–3:00 PM", "Budget Prep"),
    ("Divya Rao", "Mon 21 Sep", "4:00–5:00 PM", "Blocked"),
    ("Divya Rao", "Tue 22 Sep", "9:00–9:15 AM", "Quick Call with Arjun"),
    ("Divya Rao", "Tue 22 Sep", "11:00 AM–12:00 PM", "Internal Budget Review"),
    ("Divya Rao", "Wed 23 Sep", "1:00–2:00 PM", "Blocked"),
    ("Divya Rao", "Thu 24 Sep", "9:00–10:00 AM", "Board Prep Session"),
    ("Divya Rao", "Thu 24 Sep", "2:00–3:00 PM", "Blocked"),
    ("Divya Rao", "Fri 25 Sep", "10:00–11:00 AM", "Blocked"),
]

EMAIL_THREADS = {
    "Vendor List": [
        ("Mon 21 Sep, 9:50 AM", "Raghav Sethi → Arjun Malhotra", "Following up from the sync — can you send the updated vendor list today?"),
        ("Mon 21 Sep, 5:40 PM", "Arjun Malhotra → Raghav Sethi", "Running behind, will send first thing tomorrow morning instead."),
        ("Tue 22 Sep, 9:15 AM", "Raghav Sethi → Arjun Malhotra", "No worries, whenever you get a chance today works."),
        ("Tue 22 Sep, 6:30 PM", "Arjun Malhotra → Raghav Sethi", "Sorry, got pulled into board prep — will send by tomorrow (Wednesday) morning for sure."),
        ("Wed 23 Sep, 8:45 AM", "Raghav Sethi → Arjun Malhotra", "Just checking — still good for this morning?"),
    ],
    "Q3 Campaign Deck": [
        ("Mon 21 Sep, 11:00 AM", "Neha Kapoor → Arjun Malhotra", "Deck’s coming together, still targeting Wednesday for your review."),
        ("Tue 22 Sep, 4:15 PM", "Neha Kapoor → Arjun Malhotra", "Heads up — shifting the review to Thursday morning instead of Wednesday, need one more day on the data slides."),
        ("Wed 23 Sep, 10:00 AM", "Arjun Malhotra → Neha Kapoor", "Understood, Thursday morning works. What time exactly?"),
        ("Wed 23 Sep, 10:20 AM", "Neha Kapoor → Arjun Malhotra", "Let’s say 9:30 AM Thursday, before your board prep block."),
        ("Thu 24 Sep, 8:00 AM", "Neha Kapoor → Arjun Malhotra", "Deck is ready, attaching the draft ahead of our 9:30 review."),
    ],
    "Call Reschedule": [
        ("Mon 21 Sep, 1:00 PM", "Priya Nair → Arjun Malhotra", "Our scheduled call this week got bumped from our side — can you propose a new time? We’re flexible Tuesday–Thursday afternoons."),
        ("Tue 22 Sep, 3:00 PM", "Arjun Malhotra → Priya Nair", "Apologies for the delay — how about Wednesday 3:00 PM?"),
        ("Tue 22 Sep, 5:45 PM", "Priya Nair → Arjun Malhotra", "Wednesday 3 PM works on our end, confirmed."),
        ("Wed 23 Sep, 1:30 PM", "Priya Nair → Arjun Malhotra", "Quick check — still on for 3 PM today?"),
        ("Wed 23 Sep, 2:00 PM", "Arjun Malhotra → Priya Nair", "Yes, confirmed, see you at 3."),
    ],
    "Expense Variance Report": [
        ("Mon 21 Sep, 2:30 PM", "Divya Rao → Arjun Malhotra", "Starting on the July variance numbers, targeting Thursday morning for board prep as discussed."),
        ("Tue 22 Sep, 9:00 AM", "Arjun Malhotra → Divya Rao", "Actually, can I get it by Wednesday evening instead? Want time to review before Thursday."),
        ("Tue 22 Sep, 9:40 AM", "Divya Rao → Arjun Malhotra", "Wednesday evening is tight but doable, I’ll prioritize it."),
        ("Wed 23 Sep, 6:00 PM", "Divya Rao → Arjun Malhotra", "Report attached, sent as promised."),
        ("Wed 23 Sep, 6:10 PM", "Arjun Malhotra → Divya Rao", "Got it, thank you — exactly what I needed before tomorrow."),
    ],
    "Mumbai Office Lease Renewal": [
        ("Mon 21 Sep, 10:15 AM", "Facilities → All Staff", "Reminder: the Mumbai office lease renewal requires an authorized signature by Friday, 25 September."),
        ("Tue 22 Sep, 11:00 AM", "Raghav Sethi → Arjun Malhotra, Divya Rao", "Following up from the sync — has anyone confirmed who’s signing off on the Mumbai renewal? Don’t think it’s been assigned."),
        ("Wed 23 Sep, 9:30 AM", "Divya Rao → Raghav Sethi, Arjun Malhotra", "Not on my end — I believe this typically sits with Facilities directly, not us."),
        ("Thu 24 Sep, 4:00 PM", "Facilities → All Staff", "Second reminder: signature is still pending. Deadline is Friday, 25 September, end of day."),
        ("Thu 24 Sep, 4:45 PM", "Raghav Sethi → Arjun Malhotra", "This is now one day out and still unowned — can you confirm who’s handling it?"),
    ],
}

VOICE_NOTES = [
    ("Mon 21 Sep, 6:40 PM", "Need to get Raghav that vendor list, I think I said today but it might slip to tomorrow morning, remind me. Also still haven’t heard back on the Mumbai lease thing, someone needs to own that, I don’t think it’s me."),
    ("Wed 23 Sep, 8:15 AM", "Expense variance report from Divya needs to be in my hands by Wednesday evening, not Thursday, I want time to go through it before board prep. Also Meridian call — I owe Priya a time, need to lock that in today."),
]

RECENT_ACTIVITY = [
    {
        "time": "Thu 24 Sep, 4:45 PM",
        "title": "Mumbai lease still unowned",
        "detail": "Raghav asked Arjun to confirm who is handling the renewal.",
        "type": "critical",
    },
    {
        "time": "Thu 24 Sep, 8:00 AM",
        "title": "Campaign deck ready",
        "detail": "Neha sent the draft ahead of the 9:30 AM review.",
        "type": "completed",
    },
    {
        "time": "Wed 23 Sep, 6:10 PM",
        "title": "Expense report acknowledged",
        "detail": "Arjun confirmed receipt of Divya's July variance report.",
        "type": "completed",
    },
    {
        "time": "Wed 23 Sep, 2:00 PM",
        "title": "Meridian call reconfirmed",
        "detail": "Arjun reconfirmed the 3:00 PM client call with Priya.",
        "type": "confirmed",
    },
    {
        "time": "Wed 23 Sep, 8:45 AM",
        "title": "Vendor list follow-up",
        "detail": "Raghav checked whether the vendor list was still on track for the morning.",
        "type": "attention",
    },
]